// Generated by CoffeeScript 1.6.3
var IcedCoffeeScriptCompiler, iced, sysPath;

iced = require('iced-coffee-script');

sysPath = require('path');

module.exports = IcedCoffeeScriptCompiler = (function() {
  IcedCoffeeScriptCompiler.prototype.brunchPlugin = true;

  IcedCoffeeScriptCompiler.prototype.type = 'javascript';

  function IcedCoffeeScriptCompiler(config) {
    var cfg, _ref, _ref1, _ref2;
    this.config = config;
    cfg = (_ref = (_ref1 = this.config.plugins) != null ? _ref1.icedCoffeeScript : void 0) != null ? _ref : {};
    this.extension = (_ref2 = cfg.extension) != null ? _ref2 : 'iced';
    null;
  }

  IcedCoffeeScriptCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      return result = iced.compile(data);
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  IcedCoffeeScriptCompiler.prototype.include = function() {
    return [sysPath.join(__dirname, '..', 'vendor', 'iced-coffee-script.js')];
  };

  return IcedCoffeeScriptCompiler;

})();
